/**
 * AI Service for SplitVerse AI
 * Supports Google Gemini (AIzaSy...) and OpenAI (sk-...)
 * Automatically injects user financial context (balances, expenses, debts)
 */

const fs = require('fs');
const path = require('path');

const envPath = path.resolve(__dirname, '../../.env');
require('dotenv').config({ path: envPath });

function getApiKey() {
  return process.env.GEMINI_API_KEY || process.env.OPENAI_API_KEY || process.env.AI_API_KEY || '';
}

function saveApiKeyToEnv(key, provider = 'gemini') {
  const envVar = provider.toLowerCase() === 'openai' || key.startsWith('sk-') 
    ? 'OPENAI_API_KEY' 
    : 'GEMINI_API_KEY';

  process.env[envVar] = key;

  let content = '';
  if (fs.existsSync(envPath)) {
    content = fs.readFileSync(envPath, 'utf8');
  }

  const regex = new RegExp(`^${envVar}=.*$`, 'm');
  if (regex.test(content)) {
    content = content.replace(regex, `${envVar}=${key}`);
  } else {
    content += (content.length && !content.endsWith('\n') ? '\n' : '') + `${envVar}=${key}\n`;
  }

  fs.writeFileSync(envPath, content, 'utf8');
  return { success: true, provider: envVar, saved: true };
}

async function callGemini(apiKey, systemPrompt, userMessage, history = []) {
  const modelsToTry = [
    'gemini-3.5-flash-lite',
    'gemini-3-flash-preview',
    'gemini-3.6-flash',
    'gemini-flash-latest'
  ];

  const contents = [];

  // Add system instruction
  contents.push({
    role: 'user',
    parts: [{ text: `[System Instructions & Persona]: ${systemPrompt}\n\nPlease acknowledge and abide by these instructions in all subsequent responses.` }]
  });
  contents.push({
    role: 'model',
    parts: [{ text: 'Understood. I am ready to act as your SplitVerse AI assistant according to those instructions.' }]
  });

  // Add conversation history
  if (Array.isArray(history)) {
    for (const h of history.slice(-6)) {
      if (h.sender === 'user' || h.role === 'user') {
        contents.push({ role: 'user', parts: [{ text: h.text || h.content || '' }] });
      } else if (h.sender === 'ai' || h.role === 'model' || h.role === 'assistant') {
        contents.push({ role: 'model', parts: [{ text: h.text || h.content || '' }] });
      }
    }
  }

  // Add current query
  contents.push({
    role: 'user',
    parts: [{ text: userMessage }]
  });

  let lastError = null;

  for (const model of modelsToTry) {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

    try {
      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents,
          generationConfig: {
            temperature: 0.7,
            maxOutputTokens: 1000
          }
        })
      });

      if (!response.ok) {
        const errText = await response.text();
        if (response.status === 404 || response.status === 503 || response.status === 429) {
          // If model not found or temporary 503 spike, try next candidate
          lastError = new Error(`Gemini ${model} status ${response.status}: ${errText}`);
          continue;
        }
        throw new Error(`Gemini API error (${response.status}): ${errText}`);
      }

      const data = await response.json();
      const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!text) {
        throw new Error('No response text generated by Gemini.');
      }

      return text;
    } catch (err) {
      lastError = err;
      if (err.message && (err.message.includes('404') || err.message.includes('503') || err.message.includes('429'))) {
        continue;
      }
      throw err;
    }
  }

  throw lastError || new Error('Failed to generate response across all Gemini model versions.');
}

async function callOpenAI(apiKey, systemPrompt, userMessage, history = []) {
  const url = 'https://api.openai.com/v1/chat/completions';

  const messages = [
    { role: 'system', content: systemPrompt }
  ];

  if (Array.isArray(history)) {
    for (const h of history.slice(-6)) {
      const role = (h.sender === 'user' || h.role === 'user') ? 'user' : 'assistant';
      messages.push({ role, content: h.text || h.content || '' });
    }
  }

  messages.push({ role: 'user', content: userMessage });

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: 'gpt-4o-mini',
      messages,
      temperature: 0.7,
      max_tokens: 1000
    })
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`OpenAI API error (${response.status}): ${errText}`);
  }

  const data = await response.json();
  const text = data?.choices?.[0]?.message?.content;
  if (!text) {
    throw new Error('No response text generated by OpenAI.');
  }

  return text;
}

async function generateAIAnswer({ query, userContext = {}, history = [], customApiKey = '', agentType = 'accountant' }) {
  const apiKey = (customApiKey || getApiKey()).trim();

  // If no API key provided, signal caller to use smart local fallback
  if (!apiKey) {
    return {
      usedLiveLLM: false,
      text: null,
      message: 'No API key configured. Using local offline AI engine.'
    };
  }

  const isGemini = apiKey.startsWith('AIzaSy') || (!apiKey.startsWith('sk-'));

  const systemPrompt = `You are SplitVerse AI, the world's most advanced AI-powered fintech assistant and household operating system designed for Indian users, roommates, travelers, and teams.
Keep your answers friendly, concise, mathematically sharp, and helpful. Use Indian Rupees (₹) for currency.
User financial snapshot:
- Total You Owe: ₹${userContext.youOwe || 0}
- Total Owed to You: ₹${userContext.youAreOwed || 0}
- Net Balance: ₹${userContext.netBalance || 0}
- Active Groups: ${userContext.groupCount || 1}
Agent Role: ${agentType.toUpperCase()}
Give clear, actionable insights with bullet points or numbers when helpful.`;

  try {
    let resultText = '';
    if (isGemini) {
      resultText = await callGemini(apiKey, systemPrompt, query, history);
    } else {
      resultText = await callOpenAI(apiKey, systemPrompt, query, history);
    }

    return {
      usedLiveLLM: true,
      provider: isGemini ? 'Google Gemini' : 'OpenAI',
      text: resultText
    };
  } catch (err) {
    console.error('Live AI generation failed:', err.message);
    return {
      usedLiveLLM: false,
      error: err.message,
      text: null
    };
  }
}

module.exports = {
  getApiKey,
  saveApiKeyToEnv,
  generateAIAnswer
};
